{
 "title": "VPN Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Established Connections",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"ipsec\"} |= \"established\""
    }
   ]
  },
  {
   "title": "Closed connections",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"ipsec\"} |= \"closed\""
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"ipsec\"} |= \"timeout\" |= \"retransmit\" |= \"AUTH_FAILED\" |= \"deleting\" |= \"NO_PROPOSAL_CHOSEN\" [5m])"
    }
   ]
  }
 ]
}